// Shared CV data for Sumit Kumar's portfolio
window.CV = {
  name: "Sumit Kumar",
  first: "SUMIT",
  last: "KUMAR",
  role: "AI / ML Engineer",
  tagline: "Building scalable AI systems & data-driven solutions.",
  location: "Greater Noida, India",
  email: "sumitchoudhary2812@gmail.com",
  phone: "+91 9430262920",
  github: "github.com/Sumitkr28",
  linkedin: "linkedin.com/in/sumit-kumar2812",
  about:
    "Computer Science undergraduate with strong foundations in Data Structures, Algorithms, and Object-Oriented Programming. Skilled in Python, machine learning, and data analysis with experience in AI agents, LLM-based applications, and scalable backend systems. A quick learner eager to build scalable AI systems and data-driven solutions.",
  skills: {
    "AI & Machine Learning": ["Deep Learning", "Supervised Learning", "Model Evaluation", "Prompt Engineering", "Predictive Modeling"],
    "GenAI & LLMs": ["AI Agents", "MCP Server", "RAG Pipelines", "Agent Orchestration", "LLM Integration", "Embeddings", "FAISS"],
    "Python & Libraries": ["Python", "NumPy", "Pandas", "Scikit-learn", "TensorFlow", "XGBoost", "LangChain", "Flask"],
    "Backend & Systems": ["API Design", "Scalable Pipelines", "Tool Calling", "CI/CD", "Backend Integration"],
    "Data Science": ["EDA", "Statistical Analysis", "Data Processing", "Visualization", "Automation"],
    "Cloud & Security": ["AWS (S3, EC2)", "Docker", "Kubernetes", "Git", "OAuth2.1", "RBAC", "SPIFFE", "mTLS"],
  },
  skillsMarquee: ["PYTHON", "LLMs", "RAG", "AI AGENTS", "TENSORFLOW", "DOCKER", "MCP", "FAISS", "LANGCHAIN", "AWS", "XGBOOST", "PROMPT ENGINEERING"],
  experience: [
    {
      role: "AI & Machine Learning Intern",
      company: "Kloud Technology Works Pvt Ltd",
      period: "Mar 2026 — Present",
      stack: ["Python", "OAuth2.1", "LLM Integration", "AI Agent", "SPIFFE", "mTLS", "MCP Server"],
      points: [
        "Designed AI agent workflows using MCP server integrated with Claude AI for automation and task execution.",
        "Built secure backend APIs on AuthSec.ai and AuthNull using OAuth2.1 and mTLS, handling 5K+ requests/day.",
        "Implemented SPIFFE-based identity, improving service authentication efficiency by 30%.",
        "Integrated LLM pipelines, reducing response latency by 25% and improving task accuracy.",
      ],
    },
  ],
  projects: [
    {
      num: "01",
      title: "Zora AI",
      sub: "GenAI · Streaming Chat Assistant",
      date: "2026",
      img: "project-images/zora.png",
      stack: ["Next.js 14", "TypeScript", "Gemini 2.5 Flash", "LLM", "RAG"],
      metric: "Live",
      metricLabel: "on Vercel",
      repo: "https://github.com/Sumitkr28/zora-ai",
      demo: "https://zora-chatbot.vercel.app/",
      points: [
        "Built a free-tier AI chat assistant streaming token-by-token responses from Google's Gemini 2.5 Flash.",
        "Persisted conversations in Firestore with Google & passwordless email auth, plus an instant guest mode.",
        "Added multimodal uploads — images, PDFs, audio & video — via the Gemini Files API, with multi-key failover.",
      ],
    },
    {
      num: "02",
      title: "SafeTrace",
      sub: "ML Security · URL Threat Analyzer",
      date: "2026",
      img: "project-images/safetrace.png",
      stack: ["Next.js", "FastAPI", "XGBoost", "LightGBM", "Playwright", "SHAP"],
      metric: "<5s",
      metricLabel: "verdict",
      repo: "https://github.com/Sumitkr28/Project--SafeTrace",
      demo: "https://safetrace-ai.vercel.app/",
      points: [
        "Detects phishing, malware & defacement URLs in under 5 seconds with explainable, evidence-backed verdicts.",
        "Runs a stacking ensemble (XGBoost, LightGBM, CatBoost + SHAP) beside a headless-browser forensic analyzer.",
        "Inspects live screenshots, domain age, fake login forms & brand impersonation; cross-checks Google Safe Browsing & URLhaus.",
      ],
    },
    {
      num: "03",
      title: "Credit Card Fraud Detection",
      sub: "Data Science · Classification",
      date: "Aug 2025",
      img: "project-images/credit-fraud.png",
      stack: ["Python", "Pandas", "Matplotlib", "Seaborn", "Power BI"],
      metric: "90%+",
      metricLabel: "precision",
      repo: "https://github.com/Sumitkr28",
      demo: "",
      points: [
        "Built ML classification & regression models with cross-validation achieving 90%+ precision on imbalanced data.",
        "Performed EDA to uncover trends, patterns, and outliers.",
        "Created visual dashboards using Matplotlib and Power BI to present fraud trends.",
      ],
    },
  ],
  education: {
    school: "Greater Noida Institute of Technology",
    degree: "B.Tech, Computer Science & Engineering",
    period: "2022 — 2026",
  },
  certifications: [
    { name: "Data Structures & Algorithms", org: "E&ICT Academy, IIT Kanpur", date: "Jul 2025" },
    { name: "Data Science with Python", org: "E&ICT Academy, IIT Kanpur", date: "Aug 2025" },
    { name: "Artificial Intelligence Fundamentals", org: "IBM", date: "Oct 2025" },
    { name: "Data Analytics Job Simulation", org: "Deloitte (Forage)", date: "Jan 2026" },
    { name: "Software Engineering Job Simulation", org: "JPMorgan Chase & Co.", date: "Jan 2026" },
  ],
};
