// Shared CV data for Sumit Kumar's portfolio
window.CV = {
  name: "Sumit Kumar",
  first: "SUMIT",
  last: "KUMAR",
  role: "AI / ML Engineer",
  tagline: "Building scalable AI systems & data-driven solutions.",
  location: "Greater Noida, India",
  email: "sumitchoudhary2812@gmail.com",
  phone: "+91 9430262920",
  github: "github.com/Sumitkr28",
  linkedin: "linkedin.com/in/sumit-kumar2812",
  about:
    "Computer Science graduate (B.Tech 2026) specializing in Machine Learning and Generative AI — building AI agents, RAG pipelines, secure backend services, and scalable software with Python, FastAPI, TensorFlow, and LangGraph.",
  skills: {
    "Languages": ["Python", "Java", "JavaScript", "TypeScript", "SQL"],
    "Machine Learning": ["Supervised Learning", "Classification", "Regression", "Feature Engineering", "Model Evaluation", "Model Deployment", "Ensemble Learning (XGBoost, LightGBM, CatBoost)"],
    "GenAI & LLMs": ["AI Agents", "Multi-Agent Orchestration", "MCP Server", "RAG", "Vector Embeddings", "Semantic Search", "FAISS", "Tool Calling", "LLM Integration (Claude, Gemini, Llama)"],
    "Frameworks & Libraries": ["PyTorch", "TensorFlow", "Scikit-learn", "Pandas", "NumPy", "LangGraph", "LangChain", "Next.js", "React", "Flask"],
    "Data Engineering, MLOps & Cloud": ["NLP", "EDA", "Data Pipelines", "MLOps", "Docker", "Kubernetes", "AWS (EC2, S3)", "PostgreSQL", "CI/CD"],
    "Backend & Security": ["FastAPI", "REST APIs", "Microservices", "OAuth 2.1", "JWT", "SPIFFE", "MFA", "Git", "System Design", "Distributed Systems"],
  },
  skillsMarquee: ["PYTHON", "LANGGRAPH", "AI AGENTS", "RAG", "GEMINI", "FASTAPI", "MCP", "TENSORFLOW", "PYTORCH", "DOCKER", "KUBERNETES", "XGBOOST", "OAUTH 2.1", "EMBEDDINGS"],
  experience: [
    {
      role: "AI/ML Intern",
      company: "Kloud Technology Works Pvt. Ltd.",
      period: "Mar 2026 — Present",
      stack: ["Python", "AI Agents", "MCP Server", "API", "OAuth 2.1", "mTLS", "PostgreSQL", "Azure Database", "Docker", "Kubernetes", "Microservices"],
      points: [
        "Identity-security firm building push-based MFA — designing AI agents, microservices, and secure backend services.",
        "Designed AI agent workflows and MCP server integrations using Claude AI to automate business and engineering tasks.",
        "Built secure MFA backend microservices with OAuth 2.1, mTLS, SPIFFE, Active Directory & PostgreSQL — serving 3K+ requests/day — while contributing to microservice migration, consolidation, and authentication-platform modernization.",
        "Integrated LLM pipelines that cut response latency by 25% while improving task accuracy.",
      ],
    },
    {
      role: "Creator & AI Engineer",
      company: "Xorvion AI — Applied AI Studio",
      period: "May 2026 — Present",
      stack: ["Next.js", "TypeScript", "Python", "AI Agents", "LLMs", "RAG", "FastAPI", "Vercel"],
      points: [
        "<a href='https://xorvion-ai.vercel.app/' target='_blank' rel='noopener'>Xorvion AI</a> is my personal applied AI workspace where I design, build, and deploy production-ready AI applications, AI agents, and secure backend systems.",
        "Built and deployed four end-to-end AI products: Mergent AI, HelixOS, Zora AI, and SafeTrace AI — covering AI agents, LLM workflows, code intelligence, and cybersecurity.",
        "Designed multi-agent systems with reasoning and memory, model fine-tuning, and data pipelines for scraping, labeling, and evaluation.",
        "Drive end-to-end product development — from LLM integration and backend APIs to UI design and deployment on Vercel.",
      ],
    },
  ],
  projects: [
    {
      num: "01",
      title: "Zora AI",
      sub: "GenAI · Streaming Chat Assistant",
      date: "2026",
      img: "project-images/zora.png",
      stack: ["Next.js 14", "TypeScript", "Gemini 3.1 Flash Lite", "LLM", "RAG"],
      metric: "Live",
      metricLabel: "on Vercel",
      repo: "https://github.com/Sumitkr28/zora-ai",
      demo: "https://zora-chatbot.vercel.app/",
      points: [
        "Built a free-tier AI chat assistant streaming token-by-token responses from Google's Gemini 3.1 Flash Lite.",
        "Persisted conversations in Firestore with Google & passwordless email auth, plus an instant guest mode.",
        "Added multimodal uploads — images, PDFs, audio & video — via the Gemini Files API, with multi-key failover.",
      ],
    },
    {
      num: "02",
      title: "HelixOS AI",
      sub: "GenAI · Multi-Agent Business OS",
      date: "Jun 2026",
      img: "project-images/helixos.png?v=2",
      stack: ["Next.js", "FastAPI", "LangGraph", "Gemini", "Supabase", "PostgreSQL"],
      metric: "8",
      metricLabel: "AI agents",
      repo: "https://github.com/Sumitkr28/HelixOS-AI",
      demo: "https://helixos-ai.vercel.app/",
      points: [
        "Built a full-stack multi-agent AI platform where 8 specialist agents autonomously plan, execute, evaluate, and learn across continuous business-growth cycles.",
        "Orchestrated LangGraph agent handoffs with human-in-the-loop approval and full observability of every decision, tool, and token cost.",
        "Implemented a hybrid RAG architecture with vector embeddings, semantic retrieval, and long-term agent memory across 4 tracked KPIs on a free-tier stack (Vercel, Supabase, Gemini).",
      ],
    },
    {
      num: "03",
      title: "Mergent AI",
      sub: "Agentic AI · Microservice Migration",
      date: "May 2026",
      img: "project-images/mergent.png?v=2",
      stack: ["Python", "LangGraph", "FastAPI", "GitHub API", "RAG", "Embeddings"],
      metric: "7",
      metricLabel: "agent pipeline",
      repo: "https://github.com/Sumitkr28/Mergent-ai",
      demo: "https://mergent-ai.vercel.app/",
      points: [
        "Built an AI multi-agent platform that automates microservice migration analysis — turning weeks of manual architecture review into minutes.",
        "Built repository-aware RAG pipelines generating embeddings from source code, APIs, and docs for semantic search and context-grounded migration across Spring Boot, Node.js, Python, and Go.",
        "Architected a 7-agent pipeline with streamed live progress, schema-validated structured output, live GitHub ingestion, before/after diagrams, PDF reports, and Jira task export.",
      ],
    },
    {
      num: "04",
      title: "SafeTrace",
      sub: "ML Security · URL Threat Detection",
      date: "Apr 2026",
      img: "project-images/safetrace.png",
      stack: ["Python", "FastAPI", "XGBoost", "LightGBM", "CatBoost", "Playwright", "SHAP"],
      metric: "95%+",
      metricLabel: "accuracy",
      repo: "https://github.com/Sumitkr28/Project--SafeTrace",
      demo: "https://safetrace-ai.vercel.app/",
      hidden: true,
      points: [
        "Built an AI-powered URL threat detection platform achieving 95%+ accuracy (F1 > 0.95) using a stacking ensemble of XGBoost, LightGBM, CatBoost & Random Forest with SHAP-based explainability.",
        "Engineered 20+ threat features from URL heuristics, WHOIS, threat feeds, and Playwright headless-browser analysis.",
        "Built a FastAPI backend with real-time risk scoring and explainable verdicts in under 5 seconds.",
      ],
    },
    {
      num: "05",
      title: "Credit Card Fraud Detection",
      sub: "Data Science · Classification",
      date: "Aug 2025",
      img: "project-images/credit-fraud.png",
      stack: ["Python", "Pandas", "Matplotlib", "Seaborn", "Power BI"],
      metric: "90%+",
      metricLabel: "precision",
      repo: "https://github.com/Sumitkr28/Credit-Card-Fraud-Detection",
      demo: "",
      hidden: true,
      points: [
        "Built ML classification & regression models with cross-validation achieving 90%+ precision on imbalanced data.",
        "Performed EDA to uncover trends, patterns, and outliers.",
        "Created visual dashboards using Matplotlib and Power BI to present fraud trends.",
      ],
    },
  ],
  education: {
    school: "Greater Noida Institute of Technology",
    degree: "B.Tech, Computer Science & Engineering",
    period: "2022 — 2026",
  },
  certifications: [
    { name: "Data Structures & Algorithms", org: "E&ICT Academy, IIT Kanpur", date: "Jul 2025", link: "https://verify.eicta.digitalcredentials.in/b6e22e04-8cda-43e8-b5b5-683d4725eb97" },
    { name: "Data Science with Python", org: "E&ICT Academy, IIT Kanpur", date: "Aug 2025", link: "https://verify.eicta.digitalcredentials.in/9b902701-ed60-4e2c-bae9-9efe0648087b" },
    { name: "Artificial Intelligence Fundamentals", org: "IBM", date: "Oct 2025", link: "https://skills.yourlearning.ibm.com/certificate/share/408d72c024ewogICJvYmplY3RJZCIgOiAiUExBTi03OTEzRUUxREIwMzAiLAogICJsZWFybmVyQ05VTSIgOiAiNTczMjA5NVJFRyIsCiAgIm9iamVjdFR5cGUiIDogIkFDVElWSVRZIgp93fef0d4388-10" },
    { name: "Data Analytics Job Simulation", org: "Deloitte (Forage)", date: "Jan 2026", link: "https://www.theforage.com/completion-certificates/9PBTqmSxAf6zZTseP/io9DzWKe3PTsiS6GG_9PBTqmSxAf6zZTseP_m55njGah4ERWC9NuN_1769187873539_completion_certificate.pdf" },
    { name: "Software Engineering Job Simulation", org: "JPMorgan Chase & Co.", date: "Jan 2026", link: "https://www.theforage.com/completion-certificates/Sj7temL583QAYpHXD/E6McHJDKsQYh79moz_Sj7temL583QAYpHXD_m55njGah4ERWC9NuN_1769009088796_completion_certificate.pdf" },
  ],
};
